### ISSUE TITLE
JSX (TSX) registering as type with underline

### ISSUE THREAD

**Issue by samvk** [wendzhue/atom-one-dark-theme-underlined#1]
JSX (well, TSX) components are being confused with types.

![image](https://user-images.githubusercontent.com/12996081/69189704-d5939500-0aec-11ea-93db-1ac4af5352b6.png)

Not sure if there's any easy way to fix this by reading filetype, or an option to turn off "angle-bracket" syntax entirely in settings.

**Comment by wendzhue** [comment]
I will check this later. It seems that vscode treats the token `PasswordInput` as a class.

IMHO, it's better to underline a component's name. :P

**Comment by wendzhue** [comment]
![image](https://user-images.githubusercontent.com/12122021/69213239-72fad180-0b9e-11ea-947b-0c3e3d0386d8.png)

Sorry about that. It seems that vscode treats the token as type so I am afraid there's nothing I can do to help.
